trigger: none

pr:
  branches:
    include:
      - "*"  # Se activa para cualquier PR

# Usamos el pool de agentes locales; asegúrate de que "Agentes Locales" esté configurado en Azure DevOps
pool:
  name: 'Default'

stages:
  - stage: BackendBuildTest
    displayName: "Construir y testear el Backend"
    jobs:
      - job: BuildBackend
        displayName: "Construir y testear el backend (Java)"
        steps:
          # Paso para clonar el repositorio
          - checkout: self
          
          # Navegar a la carpeta del backend y ejecutar el wrapper de Maven (mvnw.cmd)
          - script: |
              cd backend\users-microservices
              dir
              call mvnw.cmd clean install -B
            displayName: "Ejecutar mvnw.cmd clean install"
          
          # Publicar resultados de tests (ajusta la ruta si es necesario)
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**\surefire-reports\TEST-*.xml'
              mergeTestResults: true
              testRunTitle: "Resultados de pruebas del Backend"
            displayName: "Publicar resultados de tests del backend"

  - stage: FrontendBuildTest
    displayName: "Construir y testear el Frontend"
    jobs:
      - job: BuildFrontend
        displayName: "Construir y testear el frontend (Angular)"
        steps:
          - checkout: self
          # Instalar Node.js (usando la versión 14.x en este ejemplo)
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: "Instalar Node.js"
          
          # Instalar dependencias y Angular CLI
          - script: |
              cd frontend
              npm install -g @angular/cli
              npm install
            displayName: "Instalar dependencias del frontend"
          
          # Ejecutar linting en Angular
          - script: |
              cd frontend
              ng lint
            displayName: "Ejecutar linting en Angular"
          
          # Construir la aplicación Angular
          - script: |
              cd frontend
              ng build --prod
            displayName: "Construir la aplicación Angular"
          
          # Ejecutar tests unitarios con cobertura
          - script: |
              cd frontend
              ng test --watch=false --browsers=ChromeHeadless --code-coverage
            displayName: "Ejecutar tests unitarios de Angular"
          
          # Publicar resultados de cobertura (ajusta la ruta según tu configuración)
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Build.SourcesDirectory)\frontend\coverage\cobertura-coverage.xml'
            displayName: "Publicar resultados de cobertura de código"
