trigger: none

pr:
  branches:
    include:
      - "*"

pool:
  name: 'Default'  # Nombre del pool que creaste para tus agentes locales

stages:
  - stage: BuildAndTestBackend
    displayName: "Construcci贸n y pruebas del Backend"
    jobs:
      - job: BuildBackend
        steps:
          - script: mvn clean install -B
            displayName: "Compilar y ejecutar tests del backend"
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              mergeTestResults: true
              testRunTitle: 'Resultados de pruebas del Backend'
            displayName: "Publicar resultados de tests del backend"

  - stage: BuildAndTestFrontend
    displayName: "Construcci贸n y pruebas del Frontend"
    jobs:
      - job: BuildFrontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: "Instalar Node.js"
          - script: |
              npm install -g @angular/cli
              npm install
            displayName: "Instalar dependencias del frontend"
          - script: ng lint
            displayName: "Ejecutar Linting en Angular"
          - script: ng build --prod
            displayName: "Construir la aplicaci贸n Angular"
          - script: ng test --watch=false --browsers=ChromeHeadless --code-coverage
            displayName: "Ejecutar tests unitarios de Angular"
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
            displayName: "Publicar resultados de cobertura de c贸digo"
