trigger:
- main

pool:  
  name: "Default"  # Usa el agente de la máquina virtual chiat
  container: openjdk:17

steps:
  # Paso 1: Clonar el repositorio
  - checkout: self  # Clona el repositorio en la pipeline

  # Paso 2: Verificar la URL del repositorio clonado
  - script: |
      echo "Verificando la URL del repositorio clonado..."
      git remote -v
    displayName: "Verificar URL del repositorio"

  # Paso 3: Verificar la versión de Node.js instalada en el servidor
  - script: |
      echo "Verificando versión de Node.js..."
      whoami
      node -v
      npm -v
    displayName: "Verificar Node.js instalado en servidor"

  # Paso 4: Verificar versión de Java y maven en el servidor
  - script: |
      echo "Verificando versión de Java..."
      java -version
      mvn -version
    displayName: "Verificar Java instalado en servidor"

  # Paso 5: Compilar frontend
  - task: CmdLine@2  
    displayName: 'Compilar Frontend'
    inputs:
      script: |
        echo "Descargando Modulos"
        npm install
        echo "Compilando Frontend..."
        npm run build:deploy
      workingDirectory: 'Pure-Line-main/frontend'

  # Paso 6: Ejecutar el script (asegúrate de que mesero.sh esté accesible)
  - script: |
      echo "Ejecutando script mesero.sh..."
      bash /home/rcerezo/Escritorio/mesero.sh  
    displayName: "Ejecutar script en mi máquina local"
