# La pipeline se activará solo en pull requests
trigger: none

pr:
  branches:
    include:
      - "*"  # Se activa para cualquier PR

stages:
  - stage: BuildAndTestBackend
    displayName: "Construcción y pruebas del Backend"
    jobs:
      - job: BuildBackend
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              options: '-B'
            displayName: "Compilar y ejecutar tests del backend"
          
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              mergeTestResults: true
              testRunTitle: 'Resultados de pruebas del Backend'
            displayName: "Publicar resultados de tests del backend"
          
          # Opcional: Agregar tareas de análisis de código (por ejemplo, SonarQube)

  - stage: BuildAndTestFrontend
    displayName: "Construcción y pruebas del Frontend"
    jobs:
      - job: BuildFrontend
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: "Instalar Node.js"
          
          - script: |
              npm install -g @angular/cli
              npm install
            displayName: "Instalar dependencias del frontend"
          
          - script: |
              ng lint
            displayName: "Ejecutar Linting en Angular"
          
          - script: |
              ng build --prod
            displayName: "Construir la aplicación Angular"
          
          - script: |
              ng test --watch=false --browsers=ChromeHeadless --code-coverage
            displayName: "Ejecutar tests unitarios de Angular"
          
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
            displayName: "Publicar resultados de cobertura de código"
