jobs:
- job: IntegrationTests
  pool:
    agent: Default
    vmImage: 'ubuntu-latest'
    name: Default
  container: 
    image: maven:3.8.7-openjdk-21
  services:
    mysql:
      image: mysql:latest
      env:
        MYSQL_ROOT_PASSWORD: "1234"
        MYSQL_DATABASE: "tienda_db"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "1234"
      ports:
      - 3306:3306
  steps:
  - script: |
      echo "Esperando a que MySQL esté listo..."
      until nc -z localhost 3306; do echo "Waiting..."; sleep 2; done
    displayName: "Esperar a que MySQL esté listo"
  - script: |
      mvn clean test -Dspring.profiles.active=test
    workingDirectory: 'Pure-Line-main/backend/users-microservices'
    displayName: "Ejecutar pruebas del backend"
