trigger:
  - none  # Evita que se ejecute en cada push automáticamente

pr:
  branches:
    include:
      - main  # Solo se ejecuta en PRs hacia main

pool:  
  name: "Default"  # Usa el agente del servidor en AWS
  container: openjdk:17


steps:
  
  # Paso 1: Verificar la versión de Node.js instalada en el servidor
  - script: |
      echo "Verificando versión de Node.js..."
      node -v
      npm -v
      whoami
    displayName: "Verificar Node.js instalado en servidor"

  # Paso 2: Verificar versión de Java en el servidor
  - script: |
      echo "Verificando versión de Java..."
      java -version
      mvn -version
    displayName: "Verificar Java instalado en servidor"

  # Paso 3: Instalar dependencias del frontend (si fuera necesario)
  # Comentado porque en el servidor ya está instalado Node y las dependencias
  # - script: |
  #     echo "Instalando dependencias de Angular..."
  #     npm ci
  #   workingDirectory: 'Pure-Line-main/frontend'
  #   displayName: "Instalar dependencias Angular"

  # Paso 4: Ejecutar Linter en Angular (si ESLint está configurado)
  - script: |
      echo "Ejecutando Linter de Angular..."
      mvn clean install -Djavax.net.ssl.trustStore=/usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit
    workingDirectory: 'Pure-Line-main/backend/users-microservices'
    displayName: "Validar código con ESLint"

  # Paso 4: Ejecutar Linter en Angular (si ESLint está configurado)
  - script: |
      echo "Ejecutando Linter de package..."
      mvn clean package -U
    workingDirectory: 'Pure-Line-main/backend/users-microservices'
    displayName: "Validar código con mvn"
  
  # Paso 6: Ejecutar pruebas en el backend con Maven
  #- script: |
  #    echo "Ejecutando pruebas del backend con Maven..."
  #    mvn -X test -Dspring.profiles.active=test || exit 0
  #  workingDirectory: 'Pure-Line-main/backend/users-microservices'
  #  displayName: "Ejecutar pruebas del backend"

  # Paso 7: Finalizar con éxito si todo va bien
  - script: echo "Validaciones completadas exitosamente"
    displayName: "Finalizar pipeline con éxito"
 