trigger:
  - none  # Evita que se ejecute en cada push automáticamente

pr:
  branches:
    include:
      - main  # Solo se ejecuta en PRs hacia main

pool:  
  name: "local-JLA"  # Usa el agente del servidor en AWS

steps:
  - script: mysql -h localhost -u root -p1234 -e "SELECT VERSION();"     
    displayName: 'Mostrar el usuario actual'

  - script: mysql -h localhost -u root -p1234 -e "SHOW DATABASES;"     
    displayName: 'Mostrar el usuario actual'

  - script: mysql -h localhost -u root -p1234 -e "SELECT CURRENT_USER();"    
    displayName: 'Mostrar el usuario actual'
  
  # Paso 1: Verificar la versión de Node.js instalada en el servidor
  - script: |
      echo "Verificando versión de Node.js..."
      node -v
      npm -v
    displayName: "Verificar Node.js instalado en servidor"

  # Paso 2: Verificar versión de Java en el servidor
  - script: |
      echo "Verificando versión de Java..."
      java -version
      mvn -version
    displayName: "Verificar Java instalado en servidor"

  # Paso 3: Instalar dependencias del frontend (si fuera necesario)
  # Comentado porque en el servidor ya está instalado Node y las dependencias
  # - script: |
  #     echo "Instalando dependencias de Angular..."
  #     npm ci
  #   workingDirectory: 'Pure-Line-main/frontend'
  #   displayName: "Instalar dependencias Angular"

  # Paso 4: Ejecutar Linter en Angular (si ESLint está configurado)
  - script: |
      echo "Ejecutando Linter de Angular..."
      npm run lint || echo "ESLint no configurado o con errores"
    workingDirectory: 'Pure-Line-main/frontend'
    displayName: "Validar código con ESLint"

  # Paso 5: Instalar dependencias del backend (si fuera necesario)
  #  Comentado porque Java y Maven ya están en el servidor
  # - script: |
  #     echo "Instalando dependencias del backend..."
  #     mvn clean install -DskipTests
  #   workingDirectory: 'Pure-Line-main/backend'
  #   displayName: "Instalar dependencias Maven"

  # Paso 6: Ejecutar pruebas en el backend con Maven
  - script: |
      echo "Ejecutando pruebas del backend con Maven..."
      mvn test -Dspring.profiles.active=test
    workingDirectory: 'Pure-Line-main/backend/users-microservices'
    displayName: "Ejecutar pruebas del backend"

  # Paso 7: Finalizar con éxito si todo va bien
  - script: echo "Validaciones completadas exitosamente"
    displayName: "Finalizar pipeline con éxito"
 