trigger: none  # No se ejecuta en cada push, solo en PRs

pr:
  branches:
    include:
      - main  # Se ejecuta en PRs hacia la rama main

jobs:
- job: PullRequestValidation
  displayName: 'Validación de Pull Request'
  pool:
    name: 'Default'  # Asegúrate de que este nombre sea correcto

  steps:

    # Verificar la versión de Java instalada (solo para depuración)
    - script: |
        echo "Verificando versión de Java..."
        java -version
        echo "JAVA_HOME está en: $JAVA_HOME"
      displayName: 'Verificar versión de Java en el servidor'

    # Paso 1: Validar el código Angular (sin compilar)
    - task: NodeTool@0
      displayName: 'Usar Node.js 22'
      inputs:
        versionSpec: '22.x'

    - script: |
        echo "Instalando dependencias de Angular..."
        npm install
      workingDirectory: 'Pure-Line-main/frontend'  # Ajusta si es necesario
      displayName: 'Instalar dependencias de Angular'

    - script: |
        echo "Ejecutando Linter de Angular..."
        npm run lint
      workingDirectory: 'Pure-Line-main/frontend'
      displayName: 'Validar código con ESLint'

    # Paso 2: Validar el backend con Maven
    - script: |
        echo "Ejecutando pruebas de backend con Maven..."
        mvn clean test
      workingDirectory: 'Pure-Line-main/backend'  # Ajusta si es necesario
      displayName: 'Ejecutar pruebas de Java con Maven'

    # Paso 3: Finalización y éxito
    - script: echo " Validación de PR completada con éxito"
      displayName: 'Finalización exitosa'
 